= Uke 5
#include "week5/task1.typ"
#include "week5/task2.typ"
#include "week5/task4.typ"
#include "week5/task5.typ"
#include "week5/task7.typ"
#include "week5/task14.typ"
#include "week5/task20.typ"
#include "week5/task21.typ"
#include "week5/task22.typ"
#include "week5/task23.typ"
#include "week5/task27.typ"
#include "week5/task29.typ"
#include "week5/task32.typ"
#include "week5/task36.typ"
